/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.*;
import com.sun.xml.internal.ws.util.StringUtils;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raulpenate
 */
public class panel extends javax.swing.JFrame {

    //Variables para valores estadisticos
    double maximo = 0, minimo = 0, total = 0, promedio = 0;
    int cantidad = 0;
    //MD de los paneles
    DefaultTableModel mdSucursal = new DefaultTableModel();
    DefaultTableModel mdVentas = new DefaultTableModel();
    DefaultTableModel mdCuatril = new DefaultTableModel();
    DefaultTableModel mdBuscador = new DefaultTableModel();
    //Listas de los objetos
    ArrayList<Sucursal> lSucursal = new ArrayList<>();
    ArrayList<Venta> lVenta = new ArrayList<>();
    ArrayList<Persona> lCaj = new ArrayList<>();

    //Generador de las columnas de las tablas de los panales
    public void cargarColumnaTablas() {
        //Tabla Sucursal
        String[] cabezaSucursal = {"Sede", "Nombre", "Gerente"};
        for (int i = 0; i < cabezaSucursal.length; i++) {
            mdSucursal.addColumn(cabezaSucursal[i]);
        }
        jtableSucursal.setModel(mdSucursal);
        //Tabla Ventas
        String[] cabezaVentas = {"Cliente", "Vendedor", "Compra", "Precio", "Fecha vendido"};
        for (int i = 0; i < cabezaVentas.length; i++) {
            mdVentas.addColumn(cabezaVentas[i]);
        }
        jtableVentas.setModel(mdVentas);
        //Tabla Cuatril
        String[] cabezaCuatril = {"Mínimo", "Cuartil Uno", "Cuartil Dos", "Cuartil Tres", "Máximo"};
        for (int i = 0; i < cabezaCuatril.length; i++) {
            mdCuatril.addColumn(cabezaCuatril[i]);
        }
        jtblCuatriles.setModel(mdCuatril);
    }

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        cargarColumnaTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadioButtons = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        radioGrupoCLientes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spSucursales = new javax.swing.JSpinner();
        spVentas = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableSucursal = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableVentas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlValorMaximo = new javax.swing.JLabel();
        jlblValorMinimo = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblPromedio = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jrMayorQue = new javax.swing.JRadioButton();
        jrMenorQue = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarPrecios = new javax.swing.JToggleButton();
        spValorUno = new javax.swing.JSpinner();
        spValorDos = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jtxtBuscarCLiente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        radioNombre = new javax.swing.JRadioButton();
        radioApellido = new javax.swing.JRadioButton();
        btnBuscarClientes = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jtxtBuscarEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        radioNombreEmpleado = new javax.swing.JRadioButton();
        radioApellidoEmpleado = new javax.swing.JRadioButton();
        btnBuscarEmpleados = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtableBuscador = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblCuatriles = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Venta de Carros");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear"));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Sucursales:");

        spSucursales.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        spVentas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 5));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Ventas:");

        btnGenerar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerar)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addComponent(spSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerar))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla Sucursal"));

        jtableSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableSucursalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableSucursal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla Ventas"));

        jScrollPane2.setViewportView(jtableVentas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Máximo:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setText("Mínimo:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setText("Total:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("Promedio:");

        jlValorMaximo.setText("0.00$");

        jlblValorMinimo.setText("0.00$");

        jlblTotal.setText("0.00$");

        jlblPromedio.setText("0.00$");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblPromedio))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTotal))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblValorMinimo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jlValorMaximo)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlValorMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlblValorMinimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlblPromedio))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        grupoRadioButtons.add(jrMayorQue);
        jrMayorQue.setText("<=");

        grupoRadioButtons.add(jrMenorQue);
        jrMenorQue.setSelected(true);
        jrMenorQue.setText(">=");
        jrMenorQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMenorQueActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Seleccione orden");

        btnBuscarPrecios.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnBuscarPrecios.setText("Buscar");
        btnBuscarPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPreciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(spValorUno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrMenorQue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrMayorQue, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spValorDos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnBuscarPrecios)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrMenorQue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrMayorQue))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(spValorUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spValorDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarPrecios)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Precios", jPanel7);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Seleccione:");

        radioGrupoCLientes.add(radioNombre);
        radioNombre.setSelected(true);
        radioNombre.setText("Nombre:");

        radioGrupoCLientes.add(radioApellido);
        radioApellido.setText("Apellido");

        btnBuscarClientes.setText("Buscar");
        btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBuscarCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(radioNombre)
                        .addGap(18, 18, 18)
                        .addComponent(radioApellido)))
                .addGap(48, 48, 48))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel9))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnBuscarClientes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNombre)
                    .addComponent(radioApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtBuscarCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarClientes)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel6);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Seleccione:");

        buttonGroup1.add(radioNombreEmpleado);
        radioNombreEmpleado.setSelected(true);
        radioNombreEmpleado.setText("Nombre:");

        buttonGroup1.add(radioApellidoEmpleado);
        radioApellidoEmpleado.setText("Apellido");

        btnBuscarEmpleados.setText("Buscar");
        btnBuscarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(radioNombreEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(radioApellidoEmpleado)))
                .addGap(48, 48, 48))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel10))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnBuscarEmpleados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNombreEmpleado)
                    .addComponent(radioApellidoEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarEmpleados)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel12);

        jScrollPane5.setViewportView(jtableBuscador);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Buscar", jPanel9);

        jScrollPane4.setViewportView(jtblCuatriles);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Cuartiles", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane2)
                    .addComponent(jTabbedPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        //GENERAR TABLAS
        try {

            //Se resetea datos anteriores para que no se repita
            mdSucursal.setRowCount(0);
            mdCuatril.setRowCount(0);
            //Genera las listas de Sucursales
            for (int i = 0; i < Integer.parseInt(spSucursales.getValue() + ""); i++) {
                //Generador random de datos
                RandonGenerator rndCajero = new RandonGenerator();
                //Generar cajeros
                lCaj = new ArrayList<>();
                for (int j = 0; j < 3; j++) {
                    this.lCaj.add(
                            new Persona(rndCajero.generadorNombrePersona(),
                                    rndCajero.generadorApellidoPersona(),
                                    rndCajero.generarDui())
                    );
                }
                //For de ventas
                lVenta = new ArrayList<>();
                for (int j = 0; j < Integer.parseInt(spVentas.getValue() + ""); j++) {
                    //Generar lista de Ventas
                    RandonGenerator rndVentas = new RandonGenerator();
                    Random rndObtenerVendedor = new Random();
                    lVenta.add(new Venta(
                            //Se genera el cliente
                            new Persona(
                                    rndVentas.generadorNombrePersona(),
                                    rndVentas.generadorApellidoPersona(),
                                    rndVentas.generarDui()),
                            //Generar vendedor
                            lCaj.get(rndObtenerVendedor.nextInt(3)),
                            //Generar carro vendido
                            rndVentas.generarCarro(),
                            //Generar precio dado
                            rndVentas.generarPrecio(),
                            //Genera fecha vendido
                            rndVentas.generarFecha())
                    );
                }
                RandonGenerator rndSucursal = new RandonGenerator();
                //Se llena lista de sucursal
                this.lSucursal.add(
                        //Se genera sucursal
                        new Sucursal(rndSucursal.generarNombreSucursal(),
                                //Se genera lugar
                                rndSucursal.generadorLugar(),
                                //Se genera gerente
                                new Persona(
                                        rndSucursal.generadorNombrePersona(),
                                        rndSucursal.generadorApellidoPersona(),
                                        rndSucursal.generarDui()),
                                //Se genera cajeros
                                lCaj,
                                lVenta));
            }

            //Se imprime Sucursal tabla
            for (int i = 0; i < lSucursal.size(); i++) {
                String[] filaSucursal = {
                    lSucursal.get(i).getNombre(),
                    lSucursal.get(i).getLugar(),
                    lSucursal.get(i).getGerente().getNombre() + " "
                    + lSucursal.get(i).getGerente().getApellido()
                };
                mdSucursal.addRow(filaSucursal);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        //GENERAR PROMEDIOS
        try {
            total = 0;
            cantidad = 0;
            minimo = lSucursal.get(0).getlVenta().get(0).getPrecio();
            //se obtiene tamaño sucursal
            for (int i = 0; i < lSucursal.size(); i++) {
                double subtotal = 0;
                //se obtiene tamaño venta
                for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                    lSucursal.get(i).getlVenta().get(j).getPrecio();
                    //se saca maximo
                    if (lSucursal.get(i).getlVenta().get(j).getPrecio() > maximo) {
                        maximo = lSucursal.get(i).getlVenta().get(j).getPrecio();
                    }
                    //se saca minimo
                    if (lSucursal.get(i).getlVenta().get(j).getPrecio() < minimo) {
                        minimo = lSucursal.get(i).getlVenta().get(j).getPrecio();
                    }
                    //se saca total
                    subtotal += lSucursal.get(i).getlVenta().get(j).getPrecio();
                    //se saca cuenta para el promedio
                    cantidad++;
                }
                total += subtotal;
            }
            //Se muestra en pantalla
            jlValorMaximo.setText(String.format("%.2f", (maximo)) + "$");
            jlblValorMinimo.setText(String.format("%.2f", (minimo)) + "$");
            jlblTotal.setText(String.format("%.2f", (total)) + "$");
            jlblPromedio.setText(String.format("%.2f", (total / cantidad)) + "$");
            //Valor del cuartil
            //100%
            double cuartilCuatro = maximo;
            //75%
            double cuartilTres = maximo * 0.75;
            //50%
            double cuartilDos = maximo * 0.50;
            //25%
            double cuartilUno = maximo * 0.25;
            //Sacar cuartil
            ArrayList<Object> lCuatrilUno = new ArrayList<>();
            ArrayList<Object> lCuatrilDos = new ArrayList<>();
            ArrayList<Object> lCuatrilTres = new ArrayList<>();
            ArrayList<Object> lCuatrilCuatro = new ArrayList<>();
            ArrayList<Object> lMinimo = new ArrayList<>();
            //Añadiendo cuartiles
            for (int i = 0; i < lSucursal.size(); i++) {
                for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                    if (lSucursal.get(i).getlVenta().get(j).getPrecio() == minimo && lSucursal.get(i).getlVenta().get(j).getPrecio() != maximo) {
                        lMinimo.add(lSucursal.get(i).getlVenta().get(j).getPrecio() + "");
                    } else {
                        lMinimo.add("");
                    }
                    if (lSucursal.get(i).getlVenta().get(j).getPrecio() <= cuartilUno) {
                        lCuatrilUno.add(lSucursal.get(i).getlVenta().get(j).getPrecio() + "");
                    } else {
                        lCuatrilUno.add("");
                    }
                    if (lSucursal.get(i).getlVenta().get(j).getPrecio() > cuartilUno && lSucursal.get(i).getlVenta().get(j).getPrecio() <= cuartilDos) {
                        lCuatrilDos.add(lSucursal.get(i).getlVenta().get(j).getPrecio() + "");
                    } else {
                        lCuatrilDos.add("");
                    }
                    if (lSucursal.get(i).getlVenta().get(j).getPrecio() > cuartilDos && lSucursal.get(i).getlVenta().get(j).getPrecio() <= cuartilTres) {
                        lCuatrilTres.add(lSucursal.get(i).getlVenta().get(j).getPrecio() + "");
                    } else {
                        lCuatrilTres.add("");
                    }
                    if (lSucursal.get(i).getlVenta().get(j).getPrecio() == cuartilCuatro) {
                        lCuatrilCuatro.add(lSucursal.get(i).getlVenta().get(j).getPrecio() + "");
                    } else {
                        lCuatrilCuatro.add("");
                    }
                }
            }

            int valorMaximo = Math.max(Math.max(lCuatrilUno.size(), lCuatrilDos.size()), Math.max(lCuatrilTres.size(), lCuatrilCuatro.size()));
            for (int i = 0; i < valorMaximo; i++) {
                String[] filaCuatril = {
                    lMinimo.get(i) + "",
                    lCuatrilUno.get(i) + "",
                    lCuatrilDos.get(i) + "",
                    lCuatrilTres.get(i) + "",
                    lCuatrilCuatro.get(i) + ""
                };
                mdCuatril.addRow(filaCuatril);
            }
        } catch (Exception ee) {
            System.out.println(ee);
        }
        //GENERAR CUARTILES
        try {

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jtableSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableSucursalMouseClicked
        try {
            //Resetar valores
            mdVentas.getDataVector().removeAllElements();
            mdVentas.fireTableDataChanged();
            mdVentas.setRowCount(0);
            //Buscar index
            int index = jtableSucursal.getSelectedRow();
            //Generar tabla ventas
            for (int i = 0; i < lVenta.size(); i++) {
                String[] filaVenta = {
                    lSucursal.get(index).getlVenta().get(i).getCliente().getNombre() + " "
                    + lSucursal.get(index).getlVenta().get(i).getCliente().getApellido(),
                    lSucursal.get(index).getlVenta().get(i).getVendedor().getNombre() + " "
                    + lSucursal.get(index).getlVenta().get(i).getVendedor().getApellido(),
                    lSucursal.get(index).getlVenta().get(i).getCarro() + "",
                    lSucursal.get(index).getlVenta().get(i).getPrecio() + "" + "$",
                    lSucursal.get(index).getlVenta().get(i).getFechaVenta()
                };
                mdVentas.addRow(filaVenta);
            }
        } catch (Exception ee) {
            System.out.println(ee);
        }
    }//GEN-LAST:event_jtableSucursalMouseClicked

    private void btnBuscarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadosActionPerformed
        try {
            this.mdBuscador.setRowCount(0);
            this.mdBuscador.setColumnCount(0);
            //Tabla Cuatril
            String[] columnaPrecio = {"Nombre", "Apellido", "DUI", "Sucursal"};
            for (int i = 0; i < columnaPrecio.length; i++) {
                this.mdBuscador.addColumn(columnaPrecio[i]);
            }
            jtableBuscador.setModel(mdBuscador);
            //IF de nombre o apellido
            if (radioNombre.isSelected()) {
                String nombre = StringUtils.capitalize(jtxtBuscarEmpleado.getText().trim());
                for (int i = 0; i < lSucursal.size(); i++) {
                    for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                        if (nombre.equals(lSucursal.get(i).getlVenta().get(j).getVendedor().getNombre())) {
                            String[] filasCliente = {
                                lSucursal.get(i).getlVenta().get(j).getVendedor().getNombre(),
                                lSucursal.get(i).getlVenta().get(j).getVendedor().getApellido(),
                                lSucursal.get(i).getlVenta().get(j).getVendedor().getDui(),
                                lSucursal.get(i).getLugar()
                            };
                            mdBuscador.addRow(filasCliente);
                        }
                    }
                }
            } else if (radioApellido.isSelected()) {
                String apellido = StringUtils.capitalize(jtxtBuscarCLiente.getText().trim());
                for (int i = 0; i < lSucursal.size(); i++) {
                    for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                        if (apellido.equals(lSucursal.get(i).getlVenta().get(j).getVendedor().getApellido())) {
                            String[] filasCliente = {
                                lSucursal.get(i).getlVenta().get(j).getVendedor().getNombre(),
                                lSucursal.get(i).getlVenta().get(j).getVendedor().getApellido(),
                                lSucursal.get(i).getlVenta().get(j).getVendedor().getDui(),
                                lSucursal.get(i).getLugar()
                            };
                            mdBuscador.addRow(filasCliente);
                        }
                    }
                }
            } else if ((radioNombre.isSelected() || radioApellido.isSelected()) && jtxtBuscarCLiente.equals("")) {
                JOptionPane.showMessageDialog(null, "El nombre/apellido no esta o no se escribío bien");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarEmpleadosActionPerformed

    private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
        try {
            this.mdBuscador.setRowCount(0);
            this.mdBuscador.setColumnCount(0);
            //Tabla Cuatril
            String[] columnaPrecio = {"Nombre", "Apellido", "DUI", "Compra"};
            for (int i = 0; i < columnaPrecio.length; i++) {
                this.mdBuscador.addColumn(columnaPrecio[i]);
            }
            jtableBuscador.setModel(mdBuscador);
            //IF de nombre o apellido
            if (radioNombre.isSelected()) {
                String nombre = StringUtils.capitalize(jtxtBuscarCLiente.getText().trim());
                for (int i = 0; i < lSucursal.size(); i++) {
                    for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                        if (nombre.equals(lSucursal.get(i).getlVenta().get(j).getCliente().getNombre())) {
                            String[] filasCliente = {
                                lSucursal.get(i).getlVenta().get(j).getCliente().getNombre(),
                                lSucursal.get(i).getlVenta().get(j).getCliente().getApellido(),
                                lSucursal.get(i).getlVenta().get(j).getCliente().getDui(),
                                lSucursal.get(i).getlVenta().get(j).getCarro()
                            };
                            mdBuscador.addRow(filasCliente);
                        }
                    }
                }
            } else if (radioApellido.isSelected()) {
                String apellido = StringUtils.capitalize(jtxtBuscarCLiente.getText().trim());
                for (int i = 0; i < lSucursal.size(); i++) {
                    for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                        if (apellido.equals(lSucursal.get(i).getlVenta().get(j).getCliente().getApellido())) {
                            String[] filasCliente = {
                                lSucursal.get(i).getlVenta().get(j).getCliente().getNombre(),
                                lSucursal.get(i).getlVenta().get(j).getCliente().getApellido(),
                                lSucursal.get(i).getlVenta().get(j).getCliente().getDui(),
                                lSucursal.get(i).getlVenta().get(j).getCarro()
                            };
                            mdBuscador.addRow(filasCliente);
                        }
                    }
                }
            } else if (radioNombre.isSelected() || radioApellido.isSelected() && jtxtBuscarCLiente.equals("")) {
                JOptionPane.showMessageDialog(null, "El nombre/apellido no esta o no se escribío bien");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarClientesActionPerformed

    private void btnBuscarPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPreciosActionPerformed
        try {
            this.mdBuscador.setRowCount(0);
            this.mdBuscador.setColumnCount(0);
            //Tabla Cuatril
            String[] columnaPrecio = {"Precio", "Auto", "Sucursal"};
            for (int i = 0; i < columnaPrecio.length; i++) {
                this.mdBuscador.addColumn(columnaPrecio[i]);
            }
            jtableBuscador.setModel(mdBuscador);
            //Busca si se selecciono el mayor o menor
            try {
                double valorUno = Double.parseDouble(spValorUno.getValue() + "");
                double valorDos = Double.parseDouble(spValorDos.getValue() + "");
                if (jrMayorQue.isSelected()) {
                    for (int i = 0; i < lSucursal.size(); i++) {
                        for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                            if ((valorUno >= lSucursal.get(i).getlVenta().get(j).getPrecio())
                                    && (lSucursal.get(i).getlVenta().get(j).getPrecio() >= valorDos)) {
                                String[] filaBuscadorPrecio = {
                                    lSucursal.get(i).getlVenta().get(j).getPrecio() + "$",
                                    lSucursal.get(i).getlVenta().get(j).getCarro(),
                                    lSucursal.get(i).getLugar()
                                };
                                this.mdBuscador.addRow(filaBuscadorPrecio);
                            }

                        }
                    }
                } else if (jrMenorQue.isSelected()) {
                    for (int i = 0; i < lSucursal.size(); i++) {
                        for (int j = 0; j < lSucursal.get(i).getlVenta().size(); j++) {
                            if ((valorUno >= lSucursal.get(i).getlVenta().get(j).getPrecio())
                                    && (valorDos <= lSucursal.get(i).getlVenta().get(j).getPrecio())) {
                                String[] filaBuscadorPrecio = {
                                    lSucursal.get(i).getlVenta().get(j).getPrecio() + "$",
                                    lSucursal.get(i).getlVenta().get(j).getCarro(),
                                    lSucursal.get(i).getLugar()
                                };
                                this.mdBuscador.addRow(filaBuscadorPrecio);
                            }

                        }
                    }
                }
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuscarPreciosActionPerformed

    private void jrMenorQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMenorQueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrMenorQueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarClientes;
    private javax.swing.JButton btnBuscarEmpleados;
    private javax.swing.JToggleButton btnBuscarPrecios;
    private javax.swing.JButton btnGenerar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup grupoRadioButtons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jlValorMaximo;
    private javax.swing.JLabel jlblPromedio;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblValorMinimo;
    private javax.swing.JRadioButton jrMayorQue;
    private javax.swing.JRadioButton jrMenorQue;
    private javax.swing.JTable jtableBuscador;
    private javax.swing.JTable jtableSucursal;
    private javax.swing.JTable jtableVentas;
    private javax.swing.JTable jtblCuatriles;
    private javax.swing.JTextField jtxtBuscarCLiente;
    private javax.swing.JTextField jtxtBuscarEmpleado;
    private javax.swing.JRadioButton radioApellido;
    private javax.swing.JRadioButton radioApellidoEmpleado;
    private javax.swing.ButtonGroup radioGrupoCLientes;
    private javax.swing.JRadioButton radioNombre;
    private javax.swing.JRadioButton radioNombreEmpleado;
    private javax.swing.JSpinner spSucursales;
    private javax.swing.JSpinner spValorDos;
    private javax.swing.JSpinner spValorUno;
    private javax.swing.JSpinner spVentas;
    // End of variables declaration//GEN-END:variables
}
